---

- hosts: localhost

  tasks:
  
  - name: setup my workstation setup repo
    git:
      repo: https://github.com/jpclaeys/workstation_setup.git
      dest: ~/git/workstation_setup
      update: no # We just need to make sure it's there
    tags: git

  - name: setup some expected dirs
    file:
      dest: "{{ item }}"
      state: directory
    loop:
    - "~/bin/"
    - "~/git/"
    tags: 
    - git
    - bash

  - name: create symlinks
    include: symlinks.yml

  - name: define additional repos
    include: repos.yml

  - name: Install other useful packages
    include: packages.yml
